### ISSUE TITLE
enable esm doesn't work a second time

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#351]
When one runs `ua disable esm`, that is also mistakenly removing the `sources.list.d/` file and the keyring file. This has at least two implications:
- you don't get back to the pre-enable situation with the ESM advertisement, because the `sources.list.d/` file is gone
- if you enable esm again, apt will fail because the keyring file is gone from `/etc/apt/trusted.gpg.d/` directory

**Comment by powersj** [comment]
The issue here is that the ESM entitlement calls on the `remove_auth_apt_repo` function. This function by default removes both the sources.list for ESM (repo_filename) and key (keyring_file). When we disable ESM we should only be removing the authorization. The key and sources.list for ESM should remain.

**Comment by OddBloke** [comment]
@powersj All of esm, cc, cis and fips call `remove_auth_apt_repo`; should these all be updated to only remove the authorisation, or is this an ESM-specific change?

**Comment by OddBloke** [comment]
OK, @blackboxsw has clarified that this is ESM-only, because we need to retain enough information to produce the MOTD messages (which we don't for other apt-based entitlements).

We will also need to consider that enable will change the suites that ESM is enabled for, so we may need to restore the original sources.list content (containing both suites) on disable.
