### ISSUE TITLE
python call in prerm

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#353]
We have this nagging feeling that the  `prerm` script which calls `migrate_apt_sources(clean=True)` might be overkill, or in the wrong place, and would like to understand better the scenarios it is addressing, or what problems it is fixing. The docstrings hint that it's perhaps about Ubuntu release upgrades, so why can't this be something in `postinst` instead? I understand the bit that we are calling code from the package to do cleanup, so if the package is really being removed, unless it's called in `prerm`, there is no code to call anymore in `postinst`. Is that the sole reason?

**Comment by blackboxsw** [comment]
Andreas, yes this was the only reason this code call was placed in prerm. I put it there as python because I wanted better unit test coverage of the functionality and I didn't want to add a number of untested bash script functions to do this cleanup in postinst.

Since old ua-tools had some semblance of unit tests, maybe we could perform some level of unit testing on the postinst script run and that would satisfy my hope to get automated test coverage on this cleanup being properly executed.

Otherwise we are in the camp of manually validating this behavior across releases.

**Comment by panlinux** [comment]
It looks like we don't have to mess with this now, since there is nothing to fix, and we didn't get a review comment in the previous upload about this call. And if we do want to change it, it's not going to be quick, as that python call will have to be replaced with a bunch of shell logic in postinst. Shall we close this?

**Comment by OddBloke** [comment]
+1
