### ISSUE TITLE
fips-updates: status after enable should not show active for fips and fips-updates

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#368]
Fips and fips-updates require the machine to be booted into a fips kernel, so it can't really be considered active right after having run `ua enable fips`. One could argue that someone could have enaled fips, rebooted, and later disabled it, but there is no fips disable command.

**Comment by OddBloke** [comment]
Could we flesh this out a little?

**Comment by OddBloke** [comment]
This issue feeds in to something I've been thinking about for a couple of weeks, which I will attempt to lay out here.

#### Problem Statement

Currently, we consider an entitlement to be in one of three states: `ACTIVE`, `INACTIVE`, or `INAPPLICABLE`. An entitlement moves from `INACTIVE` to `ACTIVE` when we *enable* it, and it moves from `ACTIVE` to `INACTIVE` when we *disable* it. An entitlement can move to or from `INAPPLICABLE` for a few different reasons: the system may have changed (e.g. booted in to a kernel we can livepatch, or upgraded to cosmic so ESM is no longer available) or the user's contract may have changed in some way.

This issue here in #368 raises one problem with the above scheme: FIPS doesn't become `ACTIVE` immediately on *enable*. But it is no longer `INACTIVE`, and it certainly isn't `INAPPLICABLE`.

#436 ("Cannot disable entitlements that are no longer applicable") reveals another: an entitlement moves from `ACTIVE` to `INAPPLICABLE` without ubuntu-advantage-client having any involvement (by which I mean, the client wasn't the driver of that state transition; it can only detect whether or not an entitlement is applicable when it next runs after whatever causes the transition has happened, and therefore can't perform any actions at transition time).

#### Proposed Solution

My proposed solution is this: instead of having a single axis, the state of an entitlement should be stored along two axes: applicability and application status. Applicability would be one of {`APPLICABLE`, `INAPPLICABLE`} and application status would be one of {`ENABLED`, `DISABLED`}.

The key here is the source of truth for each of these axes. Currently, we amalgamate three things in to our single axis: whether or not we have applied an entitlement to a system, the state of the system which informs applicability, and the state of the contract server. In the new scheme, however, applicability would be determined based *only* on whether or not the affordances from the contract server match the system's current state. Application status would be determined *only* by examining the state relevant to whether or not an entitlement has been applied to the system (e.g. apt files for repo entitlements).

This scheme would allow us to address #436 by modifying the `disable` command to only key off of application status. Currently, if an entitlement is `INAPPLICABLE` then we can't *disable* it. However, under the new schema (`APPLICABLE`, `ENABLED`) and (`INAPPLICABLE`, `ENABLED`) would both be valid source states for the *disable* transition. (The inverse would not be true of *enable*, however; its only valid source would be (`APPLICABLE`, `DISABLED`).)

This scheme would allow us to address #368 by introducing a new application status, `PENDING`. The FIPS entitlements would report `PENDING` as their application status if they have been enabled but `linux-fips` is not the running kernel. (We *could* address this under the current schema, by adding a fourth state, but that expands out the matrix of transitions we have to handle more than it does under the new proposal.)

I believe our current states map to the new schema like so:

* `ENABLED` => (`APPLICABLE`, `ENABLED`)
* `DISABLED` => (`APPLICABLE`, `DISABLED`)
* `INAPPLICABLE` => (`INAPPLICABLE`, `DISABLED`)
    * This implicit `DISABLED` is the underlying problem with the current schema.

**Comment by dpb1** [comment]
+1, I think it makes the UX more clear and it helps us keep our concerns separate.

**Comment by OddBloke** [comment]
The above refactor has landed, so I'm now looking at this issue specifically. What colour do we think "pending" should be in the status output?  Green doesn't quite look right to me:

![pending](https://user-images.githubusercontent.com/62736/59044277-de98ee80-884b-11e9-8f59-2fb594a9d975.png)

**Comment by powersj** [comment]
Let's start with the same grey as n/a and none as to not introduce any more new colors

**Comment by OddBloke** [comment]
Thanks, I'll make that change to my local work. We also agreed in stand-up that the messaging we output at the end of enabling the FIPS entitlements should inform the user what "pending" means.

**Comment by OddBloke** [comment]
I'm not entirely convinced by the grey, it makes it hard to see in amongst the "n/a"s:

![pending-2](https://user-images.githubusercontent.com/62736/59046954-f45ce280-8850-11e9-8bbf-edf1b5d7dfb9.png)

I'll push ahead with that, regardless, because it's easy to change later on.
