### ISSUE TITLE
When using --debug, secrets get sent unredacted to ubuntu-advantage.log

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#372]
When you use `--debug`, at least with `ua refresh` (to be merged still), the extra information is sent to the terminal, but also logged in `/var/log/ubuntu-advantage.log`, and the sanitization doesn't kick in.

I think when using `--debug`, it's reasonable to have it only send messages to stdout/stderr, and not the log, assuming it's easy to decouple that.

**Comment by OddBloke** [comment]
If we're ending up with unredacted messages in the log at all, that suggests that we haven't configured the logging framework in a way that reliably redacts messages.

I think not writing to the log when `--debug` is given would be papering over the underlying issue; we should ensure that we can never write secrets to the log.

(That said, we may want to paper over the issue in the short term, but we shouldn't consider that a complete fix.)

**Comment by panlinux** [comment]
I was considering that debug logs shouldn't be redacted at all, if they are sent only to the terminal.

**Comment by OddBloke** [comment]
Yeah, I agree that we shouldn't redact the console output; when I wrote "the log" above I did specifically mean "the log file". In retrospect, that is not at all clear. Apologies for the ambiguity!

**Comment by powersj** [comment]
What is the action on this bug?

**Comment by OddBloke** [comment]
At a bare minimum, we need to ensure that info that should be redacted doesn't end up in the world-readable `/var/log/ubuntu-advantage.log`.

The original proposal was to not write to the log file when `--debug` is given, which would solve the problem. However, I believe that is substantially less than ideal: suddenly, you can't rely on the log file when auditing what has happened to a system. Not only that, but it's not at all obvious that passing `--debug` would be what causes these gaps in logging to occur.

Therefore, IMO, a better solution would be to modify the way in which we perform redaction to happen further down the logging stack, so that we can be confident that _anything_ we write to the log file will be redacted.

(In my head, very vaguely, this would look something like having a custom formatter which we configure with the redactable strings; we would attach that formatter to the log file handler but not to the console handler.)

**Comment by powersj** [comment]
> At a bare minimum, we need to ensure that info that should be redacted doesn't end up in the world-readable /var/log/ubuntu-advantage.log.

This already happens. Are we aware of any further tokens that are not getting redacted? I want to be sure this is actually actionable and a known issue.

**Comment by OddBloke** [comment]
It does sound like this is fixed. However, it looks like we now redact in the console output also, meaning that users can't *possibly* get the redacted information (without digging in to our cache files). My impression is that this is not the intended behaviour, so I'll open a new issue for that.

**Comment by OddBloke** [comment]
I've opened #432
