### ISSUE TITLE
manually disabled services could be automatically re-enabled when processing contract deltas

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#452]
During `ua refresh`, `ua enable` and `ua attach` operations, ua client processes any contract deltas and enables any inactive services that represent a transition to enableByDefault: True. 

There are a couple of corner cases which may neglect that service was previsouly manually disabled by a user via ua disable:

1. person tried a not auto-enabled service and didn't want it running.
```
ua attach
ua enable X
ua disable X
# ua-contracts changes X to be enableByDefault: True
ua refresh (X gets re-enabled)
```

2. person manually disabled an auto-enabled service and detach/reattached
```
ua attach
ua disable livepatch
ua detach
ua attach       # livepatch re-enabled
```
3. if ua client refreshes get performed daily auto-enabled service gets disabled by the user, backend transitions enableByDefault -> False; enableByDefault ->True between refreshes
```
ua attach
# backend livepatch transition enableByDefault -> False
ua refresh
# backend livepatch transition enableByDefault -> True
ua refresh   # or ua enable of a different service (which triggers a refresh)
```

4. Backend introduces and new auto-enabled service, existing ua clients would auto-enable without customer intervention/agreement/knowledge.

```
ua attach
# backend adds new support service with enableByDefault:True 
ua refresh
# ua client sees 'new support service' enableByDefault == True and auto-enables it
```

## Decision

Due to discussion below, scenario 1-3 will be rejected and scenario 4 will be addressed In the following manner:
* ua attach operation will be the only operation that will auto-enable services
* ua refresh operation will print a message to the user about enabling the new recommended service

**Comment by powersj** [comment]
Scenario 1: There is a very low chance of this occurring. Not concerned about it as we do not have a huge list of services that are enabled by default.
Scenario 2: If someone re-attaches then they should expect things to be re-enabled by default. Not an issue.
Scenario 3: Similar to 1, not considering an issue.

**Comment by OddBloke** [comment]
I think using livepatch (or any existing entitlement) as a concrete example minimises the potential impact here. My concern is this: if we were to introduce a completely new entitlement that we wanted enabled by default, the current client code would enable that entitlement on any UA attached machine next time we enabled or refreshed.

That _might_ be what we want to happen, but my feeling is that as a UA user/customer I would be more than a little upset if all of my attached systems suddenly had a (potentially major) change applied to them with no warning and no intervention from me. (And if I were a UA customer who cared about compliance, I think I would be livid.)

In my opinion, the current client behaviour means that we will probably never be able to introduce a new `enableByDefault` entitlement, because doing so would impact every single UA user/customer in ways that we obviously can't test (and that they won't _know_ to test).

My proposal is fairly simple: change the semantics of `enableByDefault` to mean enableByDefault-on-attach. Once a system is attached, the owner of that system explicitly running `ua enable` should be the only way we apply new entitlements to the system.

(If we were to do this, I think it would also make sense to message about new `enableByDefault` entitlements during refresh, along the lines of "entitlement foobar is recommended by default, run 'ua enable foobar' to enable it if you want".)

**Comment by blackboxsw** [comment]
Adding Dan's scenario as scenario #4. Since agreed upon, we can make sure that #450 addresses this last scenario
