### ISSUE TITLE
ESM status is inconsistent 

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#461]
In this example UA status output varies if you are root or not.

```
multipass@t1:~$ ua status
Account: josh.powers@canonical.com
Subscription: josh.powers@canonical.com
Valid until: n/a
Technical support level: n/a

cc            entitled         n/a
cis-audit     none             inactive
esm           entitled         inactive
fips          entitled         n/a
fips-updates  none             inactive
livepatch     entitled         n/a

Enable entitlements with `ua enable <service>`
multipass@t1:~$ sudo ua status
Account: josh.powers@canonical.com
Subscription: josh.powers@canonical.com
Valid until: n/a
Technical support level: n/a

cc            entitled         n/a
cis-audit     none             inactive
esm           entitled         active
fips          entitled         n/a
fips-updates  none             inactive
livepatch     entitled         n/a

Enable entitlements with `ua enable <service>`
multipass@t1:~$ apt-cache policy ubuntu-advantage-tools 
ubuntu-advantage-tools:
  Installed: 19.5~438~git.ec0049a~ubuntu14.04.1
  Candidate: 19.5~438~git.ec0049a~ubuntu14.04.1
  Version table:
 *** 19.5~438~git.ec0049a~ubuntu14.04.1 0
        500 http://ppa.launchpad.net/canonical-server/ua-client-daily/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     10ubuntu0.14.04.3 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
```

**Comment by powersj** [comment]
Here is another example, where I try enabling a different service, and then as a result the status output varies:

https://paste.ubuntu.com/p/jwtqMc5v2c/

**Comment by blackboxsw** [comment]
I'd be curious to see  the output of the following on those systems:
cat /var/lib/ubuntu-advantage/machine-access-esm.json | jq '.localEnabled'


in theory it should be 'true' which is what non-root user relies on

**Comment by powersj** [comment]
Reproduced again, this time with jq output showing 'null':
https://paste.ubuntu.com/p/Qjq5p8Vgjf/

**Comment by OddBloke** [comment]
I have been able to reproduce this in a lxd container.

I believe the root of this problem is in delta processing (which `ua enable` triggers, as would `ua refresh`).

`action_enable` calls `contract.request_updated_contract` which in turn calls `UAContractClient.request_resource_machine_access` for each entitlement. `UAContractClient.request_resource_machine_access` writes to both the private and public `machine-access-<name>.json` files. As a consequence, the public file no longer has a value for `localEnabled`, because that's only injected during `RepoEntitlement.enable()` or `RepoEntitlement.disable()`. (And, to round it out, a missing `localEnabled` value is treated as INACTIVE in `RepoEntitlement.operational_status` when we aren't running as root.)

To address this, I propose storing the "localEnabled" status for entitlements in a separate (publicly readable) file from the `machine-access-*.json` files. This will mean that the `machine-access-*.json` files should contain only the response that we received from the contract server, so we can safely overwrite them in the code that deals with the contract service.

Thoughts?

**Comment by blackboxsw** [comment]
Odd_Bloke: +1 on separation of uaclient state (localEnabled) to avoid dirtying the cached responses from ua-contracts services. it was an abuse in the first place
