### ISSUE TITLE
ua detach as non-root user on attached machine reports unattached

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#533]
```
multipass@ua-t:~$ ua status
Account: chad.smith@canonical.com
Subscription: chad.smith@canonical.com
Valid until: n/a
Technical support level: n/a

SERVICE
cc-eal        entitled         n/a
cis-audit     none             n/a
esm           entitled         active
fips          entitled         n/a
fips-updates  none             n/a
livepatch     entitled         active

Enable entitlements with `ua enable <service>`
```

```
multipass@ua-t:~$ ua detach
This machine is not attached to a UA subscription.
See `ua attach` or https://ubuntu.com/advantage
```

**Comment by OddBloke** [comment]
I can reproduce this; going to dig in to what's causing it now.

**Comment by OddBloke** [comment]
OK, here's the problem:

* `action_disable` is decorated by `assert_attached_root`
* `assert_attached_root` checks if we are attached by calling `UAConfig.is_attached`
* `UAConfig.is_attached` checks if we have a machine token; we're attached if we do, and not if we don't
* Non-root users can no longer read the machine token, so this will always return `False` for them, causing this message to be displayed

I believe the fix is to modify `is_attached` to use the status cache if run as a non-root user.

**Comment by OddBloke** [comment]
Actually, I think a simpler fix is for `assert_attached_root` to switch the order in which it performs its checks, so it will fail for non-root users before it checks attach status.
