### ISSUE TITLE
Consolidate duplicated state in `machine-access-*.json` and `machine-token.json`

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#649]
In https://github.com/CanonicalLtd/ubuntu-advantage-client/pull/639#discussion_r294955174, @blackboxsw and I discussed `machine-access-<entitlement>.json` vs `machine-token.json`. My understanding from that discussion is that we would always expect the two to have matching content, except in cases where we have a bug that causes them to get out-of-sync.

Should we remove the `machine-access-<entitlement>.json` files and consolidate the on `machine-token.json` as our single source of truth?

**Comment by blackboxsw** [comment]
machine-access-<entitlement>,json does have the additional `resourceToken` that is not present in machine-token.json for each service/entitlement.  Maybe just FUD on my part, but if we consolidate them I get concerned about our ability to quickly triage issues related to responses that ua-contracts gives us from  the separate API routes for machine-token vs. machine-access. As it is now we have separate artfiacts easily accessible for each route we are calling on the ua-contracts service, if we consolidate them into a single file we have to do more work to debug failures by log scraping.

**Comment by OddBloke** [comment]
Setting aside `resourceToken` for a moment, if the `machine-token` response contained all of the data we need, could we stop hitting the `machine-access` routes entirely?

(Coming back to `resourceToken`: looking at an attached VM, `machineToken` in `machine-token.json` is the same as `resourceToken` in each of the `machine-access-*.json` files.)

**Comment by blackboxsw** [comment]
Yes, if `machine-token` currently contains all the data we need, we wouldn't need to call it. 
 It was originally designed by the ua-contracts folks to give them a mechanism to both track when services are enabled and be able to gate/block that access at service at enablement time. 

But, backend implementation went another way on a per-service basis. The livepatch service or apt repos will gate access to the resources directly via whatever proxy is in front of those services. Instead of blocking access to the service at ua-contracts api routes, they now block access to the actual resource if needed.

Also, since UA client hits every machine-access route right at attach (and refresh) it doesn't really give ua-contracts backend a metric of when that entitlement got enabled. But, they can rely on their backend resources to monitor apt/livepatch access attempts to determine that.

If `resourceToken` gets obtained for every service/entitlement in machine-token, we wouldn't need to call the `machine-access` route  unless ua-contracts has another need for us to do that.


As you mentioned, `machineToken` and `resourceTokens` are currently identical. That is intended to change, there should be (for security purposes) separate resourceTokens per service. I don't think ua-contracts backends have grown that feature yet.

**Comment by powersj** [comment]
@OddBloke given @blackboxsw's response, is there any action here?

**Comment by OddBloke** [comment]
@powersj Yes, I think there's an opportunity to cut the number of API calls we make during refresh substantially, because we wouldn't need to make one per entitlement. That would give us faster attach, refresh and enable.

(I just checked; on xenial, we make 4 API calls on attach. One for the actual attach, and then one for each of esm, livepatch and support. If an account is entitled to more than the free stuff, they would make more calls. We could feasibly cut this down to just 1.)

**Comment by powersj** [comment]
Moving this back out to 19.6, I don't see us doing this in 19.5.1

**Comment by blackboxsw** [comment]
I think we can drop machine-access routes in ua client now that machine-token contains resourceTokens for each entitled service:
```
{
   "resourceTokens" : [
      {
         "Type" : "esm-infra",
         "Token" : "<REDACTED>"
      },
....
   ],
```

**Comment by powersj** [comment]
@blackboxsw How much work is this?
