### ISSUE TITLE
“Refreshing contracts prior to enable” is mysterious

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/ubuntu-advantage-client#655]
```
 😌 15:26:29@~> sudo ua enable livepatch
Refreshing contracts prior to enable
Livepatch is not available for platform i686.
Supported platforms are: x86_64
 😠 15:26:32@~> 
```

The text “Refreshing contracts prior to enable” is not mentioned in [the client spec](https://docs.google.com/document/d/1ZUjKyErwJftQnT800PIWgspT9P_QgvRKhd-jnrAPycg/edit), and I don’t understand what it means. (Does “contracts” mean “subscriptions”?)

**Comment by blackboxsw** [comment]
Thank @matthewpaulthomas for the issue.
The refresh message is emitted because the UA client needs to talk to ua-contracts backend service just prior enable to make sure the ubuntu advantage contract service details haven't been changed to permit, disallow or expire a particular service.  This situation could occur if a customer extends or changes their Ubuntu Advantage licenses and, shortly afterward, attempts to enable services.

We add the message, because that round trip to ua-contracts service could take a few seconds and we want the user at the terminal to know that work is in progress.

**Comment by matthewpaulthomas** [comment]
@blackboxsw Thanks, that makes sense. Perhaps it would be clearer as something like:
```
One moment, checking your subscription first…
```
