### ISSUE TITLE
redundant conffile handling in postrm

### ISSUE THREAD

**Issue by vorlonofportland** [CanonicalLtd/ubuntu-advantage-client#687]
The u-a-t postrm script has the following code:

remove_apt_hook(){
    rm -f /etc/apt/apt.conf.d/20apt-esm-hook.conf
}

/etc/apt/apt.conf.d/20apt-esm-hook.conf is a conffile (autopromoted to one by dh).  While users probably shouldn't edit this file, it is still the case that unconditionally deleting it in the postrm is not a policy-compliant way to handle conffiles.

Ideally there would be a way to place this file under e.g. /usr/lib/apt/apt.conf.d/20apt-esm-hook.conf and have apt read it.

**Comment by vorlonofportland** [comment]
Actually I now see that this code is only called on postrm purge.  So in reality, it's policy-compliant but entirely redundant, since dpkg itself will remove the conffile on purge.

**Comment by panlinux** [comment]
Indeed, this can be cleaned up and only `/etc` files created in `postinst` or dynamically otherwise need to be handled explicitly in purge. I had a misunderstanding there.

Steps 5 and 6 are clear (https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html#details-of-removal-and-or-configuration-purging):

> 5. The conffiles and any backup files (~-files, #*# files, %-files, .dpkg-{old,new,tmp}, etc.) are removed.
> 6. postrm purge

**Comment by panlinux** [comment]
Closed by https://github.com/CanonicalLtd/ubuntu-advantage-client/pull/802
