### ISSUE TITLE
Using a test account got an immediate datetime error

### ISSUE THREAD

**Issue by BryanQuigley** [CanonicalLtd/ubuntu-advantage-client#694]
Created a new test asset/customer for this, and immediately ran into this issue.  The date is the time for the asset to expire.  Has this been tested by any test customer accounts or only Canonical employees?

ESM is still enabled, but sudo ubuntu-advantage status errors out and doesn't display status.

```pytb
ubuntu@newuaclient-1:~$ sudo ubuntu-advantage attach <>
sudo: unable to resolve host newuaclient-1
Enabling default service esm
Enabling authenticated repo: https://esm.ubuntu.com
Updating package lists
Extended Security Maintenance enabled.
This machine is now attached to 'Ubuntu Advantage'.

Traceback (most recent call last):
  File "/usr/bin/ubuntu-advantage", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.5', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 397, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 426, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 281, in action_attach
    action_status(args=None, cfg=cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 341, in action_status
    print(ua_status.format_tabular(cfg.status()))
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 260, in status
    self.write_cache('status-cache', status)
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 219, in write_cache
    content = json.dumps(content)
  File "/usr/lib/python3.4/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2020, 7, 18, 0, 0) is not JSON serializable
```

**Comment by BryanQuigley** [comment]
This for this this contact https://canonical.my.salesforce.com/003D000001uoL4V on this account
https://canonical.my.salesforce.com/001D000001mIA6A

It would also be very useful from a debugging perspective if support has some way to see on the account/contact level what a customers credential is.

**Comment by BryanQuigley** [comment]
On reboot:
ubuntu@newuaclient-1:~$ ubuntu-advantage status
This machine is not attached to a UA subscription.
See `ua attach` or https://ubuntu.com/advantage
ubuntu@newuaclient-1:~$ sudo ubuntu-advantage attach C...ea
sudo: unable to resolve host newuaclient-1
This machine is already attached to 'Incom Essential Server Testing Technologies'

**Comment by panlinux** [comment]
This last issue is probably to the cached status, since you ran the command as a regular user and not root. See issue #622

**Comment by BryanQuigley** [comment]
Indeed, sudo ubuntu-advantage status crashes with same datetime error

**Comment by OddBloke** [comment]
Bryan has given me the failing token via other channels, and I can reproduce this. As the traceback suggests, the issue comes when we attempt to write a datetime to the status cache, because Python datetimes aren't natively serialisable to JSON.

There are two options that I see here: add code to handle round-tripping dates to disk (which is a known problem; many people have obviously needed to round-trip dates to/from JSON in Python), or we could store the string representation that we would display in the JSON, and sidestep the serialisation issue.

The latter option is a simpler fix, but does mean that the exact string format used in the status display would also have to be used in the `--json` representation; this is probably a tradeoff that we shouldn't make, so I'll pursue the first option when I pick this up.
