### ISSUE TITLE
`ua status` attempts a call to the contract server even when attached

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#760]
Specifically, it fetches the resources endpoint. This is, at the very least, causing test failures during package builds (where we don't have access to the endpoint).

**Comment by powersj** [comment]
It is not clear to me what the issue is here anymore.

For unattached system, we have to reach out to the contract backend to get the list of supported services and to be able to say what is available or not.

For attached systems, maybe we need to do something better? Is this still the behavior?

Please confirm, next steps here.

**Comment by powersj** [comment]
#890 had comments that fixes this, however if it is not feel free to re-open with next steps.
