### ISSUE TITLE
`ua enable` seems to consider anything as valid while unattached

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#777]
We are unattached, and there is a list of the available services:
```
$ sudo ua status

SERVICE      AVAILABLE  DESCRIPTION
cc-eal        no         Common Criteria EAL2 Provisioning Packages
esm           yes        UA Infra: Extended Security Maintenance
fips          no         NIST-certified FIPS modules
fips-updates  no         Uncertified security updates to FIPS modules
livepatch     yes        Canonical Livepatch service

This machine is not attached to a UA subscription.
See https://ubuntu.com/advantage
```
Yet, if I try to enable something that does not exist, it tells me that in order to get it, I need a subscription, implying that it does exist and is offered:
```
$ sudo ua enable free-first-class-for-life
To use 'free-first-class-for-life' you need an Ubuntu Advantage subscription.
Personal and community subscriptions are available at no charge
See https://ubuntu.com/advantage
```

**Comment by OddBloke** [comment]
Thanks for the bug report! In the UX doc, we have the following scenario:

```
$ sudo ua enable foobar
Cannot enable ‘foobar’
For a list of services see: sudo ua status
```

I suspect we should be using that messaging for this case instead.

**Comment by panlinux** [comment]
That's the message I get if I do it after attach, but on an unattached system, it's the one I showed.

**Comment by powersj** [comment]
Update unattached output to show, for unknown services:

```
$ sudo ua enable foobar
Cannot enable ‘foobar’
For a list of services see: sudo ua status
```

For known services:

```
$ sudo ua enable livepatch
To use 'livepatch' you need an Ubuntu Advantage subscription.
Personal and community subscriptions are available at no charge
See https://ubuntu.com/advantage

```

**Comment by OddBloke** [comment]
@powersj We have a similar issue to this one for `disable`. Are you happy for `disable` to error in the same ways that `enable` will (i.e. "Cannot disable" for an unknown service, and "To use ..." for a valid service)?

(For reference, currently it shows "To use ..." regardless of service validity, like enable.)

**Comment by powersj** [comment]
Yes, let's be consistent with enable and disable and use the two different messages.

**Comment by OddBloke** [comment]
OK, @powersj, it turns out that this is potentially a little more complex than I was anticipating. Basically, we have three checks that we want to perform before an enable or disable happens (presented in no particular order):

1. is the user root?
2. is the machine attached?
3. is the service name we're given valid?

Currently, we check for root then check for attached (i.e. `[1, 2]`). To get the behaviour that we've described above, 3 needs to come before 2, so that we won't show the "unattached" message for invalid service names. The easiest way to implement this is before both checks (i.e. `[3, 1, 2]`).

Unfortunately, this leads to inconsistent behaviour for non-root users (inconsistent both with root behaviour, and internally):

```
$ ua enable foobar  # We fail at 3
Cannot enable 'foobar'
For a list of services see: sudo ua status
$ ua enable livepatch  # We pass 3, but fail at 1
This command must be run as root (try using sudo)
```

My feeling is that we either want to apply these in `[3, 2, 1]` so that the root check is the last one that triggers _but_ 2 relies on being root currently, so we can't easily do that.  As such, I propose `[1, 3, 2]` so that a non-root user will always get the pointer to `sudo`, and then root will get the behaviour specified above.

Does that sound reasonable?

**Comment by powersj** [comment]
Yes +1
