### ISSUE TITLE
Should we depend on /usr/bin/gpg?

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#797]
Since `debian/postinst` is now using gpg, we should declare it in `debian/control` as a `Depends`.
The package providing that binary changed between ubuntu releases, though:
- trusty: gnupg
- xenial: gnupg
- bionic: gpg
- eoan: gpg (presumably the next LTS too)

[AGREED] UA Client should not rely on gpg cli if we can avoid it.
This issue is addressed by PR #803

**Comment by panlinux** [comment]
The ubuntu-minimal package has a dependency on ubuntu-advantage-tools, and us adding gpg/gnupg to that chain might not be welcomed.

**Comment by OddBloke** [comment]
Yeah, I think introducing gnupg into the minimal seed would be seen very poorly.

The situation is that trusty and xenial have gnupg in the minimal seed, but everything after that does not have it. So we _can_ get away with depending on it for the trusty release, but I think we're going to need to work out a different solution for bionic and later. We may want to do that sooner rather than later, though, to avoid having to deal with upgrading between the two different modes of operation.

**Comment by panlinux** [comment]
Can we revert this gpg-in-postinst change?

**Comment by panlinux** [comment]
The current call in postinst, even with `--no-options`, is producing an error message during the installation, see https://github.com/CanonicalLtd/ubuntu-advantage-client/issues/801#issuecomment-539196819

**Comment by OddBloke** [comment]
Next steps:

* deliver a keyring per service to /u/s/keyrings
* on service enable, install the appropriate file via cp to the apt keyrings directory
