### ISSUE TITLE
help support for ua <subcmd>

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#848]
Per #847 we added a `ua help` subcommand to print usage for the top-level ua command. So `-h`, `--help` and `help` all print command usage.

Should each subcommand surface the `help` alias too?

**Comment by OddBloke** [comment]
`help` isn't an alias for `--help`, `help` is a `ubuntu-advantage` sub-command which emits the help output for `ua`. So, given these semantics, it doesn't follow that having it at the top-level implies we should have it elsewhere, because we only have a single layer of commands.

(Also, from a practical perspective: `ua attach help`, `ua enable help`, and `ua disable help` are all ambiguous because those commands take arguments. We _could_ special-case it, but that leaves us with a very confusing UX, IMO.)

**Comment by powersj** [comment]
I'm a a -1 on this. We had one specific ask, but I don't believe we should extend that decision elsewhere.
