### ISSUE TITLE
ua attach or status run into "UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 84: ordinal not in range(128)"

### ISSUE THREAD

**Issue by jpseara** [CanonicalLtd/ubuntu-advantage-client#859]
Getting the following error when running `sudo ua attach` on fully updated Trusty Server.

This is a KVM instance. Ubuntu Trusty freshly installed and upgraded to 14.04.6 LTS.

```
ubuntu@trusty:\~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty

ubuntu@trusty:\~$ uname -a
Linux trusty 3.13.0-170-generic #220-Ubuntu SMP Thu May 9 12:40:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@trusty:\~$ sudo ua --debug attach $TOKEN_HIDDEN
(...)
DEBUG: Writing file: /var/lib/ubuntu-advantage/status.json
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.5', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 486, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 516, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 335, in action_attach
    action_status(args=None, cfg=cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 426, in action_status
    print(ua_status.format_tabular(cfg.status()))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 84: ordinal not in range(128)
```

 After `sudo ua attach` is finished, same error will happen when issuing `sudo ua status`:

```
ubuntu@trusty:\~$ sudo ua status
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.5', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 486, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 516, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 426, in action_status
    print(ua_status.format_tabular(cfg.status()))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 84: ordinal not in range(128)
```

**Comment by panlinux** [comment]
`\u2014` is the long hyphen:
```
'status': u'\u2014'
```
Or:
```
"status" : "—",
```

**Comment by jpseara** [comment]
panlinux, the problematic environment system variable is the following:

`$ LC_CTYPE=pt_PT.UTF-8`

So if I issue: `$ export LC_CTYPE=en_US.UTF-8`
And then try to attach again, it will work.

I've checked the status.json files generated in each situation, and in both of them we have "status": "\u2014".

**Comment by panlinux** [comment]
Yeah, to reproduce, one has to set LC_CTYPE to a locale that is not installed on a machine. For example:
```
ubuntu@trusty-ua:~$ export LC_CTYPE=es_ES.UTF-8
ubuntu@trusty-ua:~$ sudo ua attach lolsecret
Enabling default service esm-infra
Updating package lists
ESM Infra enabled.
This machine is now attached to 'andreas.hasenack@canonical.com'.

Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.5', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 497, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 527, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 335, in action_attach
    action_status(args=None, cfg=cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 432, in action_status
    print(ua_status.format_tabular(cfg.status()))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 84: ordinal not in range(128)
```
Or do the same with plain root, without sudo, in case sudo isn't honoring that `LC_CTYPE` env var when switching to root.

**Comment by OddBloke** [comment]
OK, I've reproduced this; once attached, it's simply a matter of `LC_CTYPE=es_ES.UTF-8 ua status` to see it.

The problem here is that Python is opening the `stdout` stream with ASCII encoding in the failure case. Adding a `print(sys.stdout.encoding)` to the top of `main()` shows "UTF-8" under normal operation, and "ANSI_X3.4-1968" with the above `LC_CTYPE` set (which is ASCII, to save you also websearching to find that out).

A couple of solutions occur to me: detect when we're dealing with a non-UTF-8 output stream and emit a - instead of a —, or change the encoding that `sys.stdout` uses when program execution starts.

I have some concerns about both of those options, so before I consider any further I'm going to do what I always do when confronted with a difficult Python CLI problem: go and look at what click does.

**Comment by OddBloke** [comment]
OK, `click` doesn't handle this case gracefully either, so that's not particularly useful. (Though it does indicate that changing the encoding of the output stream isn't _clearly_ the right thing to do, else I assume they would do it.)

(For reference, it looks like this issue stopped occurring some time between trusty and eoan, as eoan's Python 3 detects UTF-8 output in both cases.)

**Comment by OddBloke** [comment]
OK, so I've been noodling on this some more, here are some more thoughts on the two potential solutions:

* the first potential solution is: change the encoding of the stdout stream to use `utf-8` unconditionally. This will silence the traceback, but will mean that terminals which truly don't support UTF-8 will get characters that they cannot display emitted. I don't know how to emulate such a terminal, so I don't know what effect this would have. I don't know when a user would have a terminal that doesn't support UTF-8, so I also don't know how likely this is to come up.

* the second potential solution is: check what the encoding of stdout is and, if it isn't `utf-8`, emit a regular ASCII "-" instead of the Unicode character that causes the problem. This should address this traceback but has a couple of drawbacks:
    * we will end up emitting the ASCII `-` in a bunch of scenarios where we _could_ emit the Unicode `—` (because Python 3.4 seems to detect unknown UTF-8 locales as only supporting ASCII); I think the most notable would be anyone running with a locale other than `en_US.UTF-8` SSH'ing into an Ubuntu machine that hasn't had any locales added (e.g. cloud images, freshly installed servers).
    * it won't protect us against any other Unicode characters in our output; the free contract uses email addresses, which [can contain UTF-8](https://en.wikipedia.org/wiki/Unicode_and_email), and IIRC the paid contracts will include company or persons name, both of which can of course include UTF-8.

I propose following the path of the second solution, at least in the short-term, to get rid of this traceback (which given that this is likely to exhibit on all cloud images will be very common, I think!), and filing separate issues for the "show — in more cases" and "we should be able to display our customers' names as a matter of basic courtesy" concerns that I raised.

**Comment by powersj** [comment]
+1 on emitting a regular dash if we are not using utf-8

**Comment by blackboxsw** [comment]
+1 on regular dash instead of em-dash when non-utf-8 locale.getpreferredencoding().   I don't expect we really care about people trying to parse "—" versus "-" in status output in general. But, since this value is also presented in status.json and `ua status --format json` output  I wonder if it is worth us trying to just use hyphen in the status output and only render em-dash in console if on utf8-preferred.
