### ISSUE TITLE
Failure to enable an entitlement potentially results in other entitlements not being enabled

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#953]
Related to #952, but a distinct issue (that can't be solved by dropping non-root status).

This doesn't always happen when a given entitlement fails. This probably isn't an indicator that the issue isn't present every time, but that we're iterating over the entitlements in an unstable order (e.g. Python dict keys).

**Comment by blackboxsw** [comment]
This case where other entitlements aren't enabled is directly related to special general Exception handling (instead of potentially expected UserFacingErrors on line 297 of the same file
https://github.com/CanonicalLtd/ubuntu-advantage-client/blob/master/uaclient/contract.py#L299L304

I'm not sure what we should do with generally unexpected Exceptions and whether we should queue them up or fail hard sooner as we are currently doing.

**Comment by blackboxsw** [comment]
@OddBloke does this approach sound good? Queue the unexpected error like we do UserFacingErrors and only raise at the end of the for loop?

**Comment by OddBloke** [comment]
I do think we should queue up the unexpected errors until the end, so that we attempt enable on all the entitlements. _But_, I also think we want to indicate to the user that we would appreciate a bug report in these cases.

We may want to do some UX thinking before we dive into implementation, though, because this will affect the output of `attach`.

**Comment by powersj** [comment]
Here is my attempt to throw something at the wall:

```
$ sudo ua attach <token>
<bad stuff happens>
<status prints out>
An unexpected error(s) occurred during attach
For more details, see the log: /var/log/...
```

Questions:
1) What kind of unexpected errors would we be talking about?
2) What is the log file they should look at?
3) Where do they file a bug? (I'm working on a decision for this one and whether we even put that in the output)

**Comment by blackboxsw** [comment]
>     1. What kind of unexpected errors would we be talking about?
 Unexpected errors might be:
      * ua-contracts server being down for maintenance resulting in timeout
      * ua-contracts server returning 503 due to not handling load while ua client iterates over each entitlement performing POSTs for each entitlement
      * unhandled logic or unseen gaps in uaclient in process_entitlement_deltas for a given entitlement type, such as unexpected values or new structure of machine-access responses from the contract server that break us.

2. /var/log/ubuntu-advantage.log for Tracebacks

3. Maybe they can file a bug at 
https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+filebug

**Comment by powersj** [comment]
Those errors seem like they could be in two categories 1) temporary, try again later and 2) something hit the fan. Should the UX then state something unexpected happen, please try your last command again and if this continues to be an issue file a bug?

**Comment by blackboxsw** [comment]
for 1) intermittent load/server down type issues, I think we could say try again later.
We already report this if we can't contact the server in the first place:
```
Failed to connect to authentication server
Check your Internet connection and try again
``` 
We could reuse that type of error if we fail to iterate over machine-access routes or if we hit any generally response errors from the contracts server during `ua refresh` etc.

Alternative:
  - we can limit our exposure to type 1 issues in this particular case as I *think* we can now drop our calls to each service's specific machine-access route (because the proper tokens for each service are provided for us in the global machine-token as of a few months ago.
I've added this comment to our existing issue about this https://github.com/CanonicalLtd/ubuntu-advantage-client/issues/649


For type 2 errors, if something hit the fan because contract server changed response format or api handshake flow and ua client doesn't cope. I think mentioning an unexpected error and check the logs and file a bug is probably the right approach.

**Comment by powersj** [comment]
@OddBloke thoughts?

**Comment by OddBloke** [comment]
OK, my thoughts are that when I said:

> But, I also think we want to indicate to the user that we would appreciate a bug report in these cases.

I should instead have filed a separate issue, as that's not directly related to the issue at hand, and I think has derailed the conversation somewhat. I've opened #983.

Beyond that, I think Josh's proposed UX looks good: we iterate over all entitlements and emit any errors that occur, then we display status, then we prompt the user to go back and look at those previous error lines and perhaps do something more.

It's worth noting that the log is not particularly user friendly as it stands today, so I don't know if directing users to it is necessarily our best bet. I'm not saying we shouldn't do it, particularly in an unknown error case, but it bears consideration.

**Comment by powersj** [comment]
Notes:

https://github.com/CanonicalLtd/ubuntu-advantage-client/blob/master/uaclient/contract.py#L299L304

* Update message with directing the user to the logs and to file a bug
* Can re-use existing UX from above comments in branch
