### ISSUE TITLE
Standard instances (non-pro) should not run attempt to auto-attach

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#974]
Currently in master, a systemd or init script calls `ua auto-attach` to attempt to auto-attach any vm to UA. 

The same ubuntu-advantage-tools package should be able to be installed on standard and Ubuntu Pro vms without resulting in an error condition at boot.

UA client needs to better discover platform type before attempting to auto-attach against ua-contracts on "standard" (non-Pro) Ubuntu instances.

**Comment by OddBloke** [comment]
I'm not sure if this is a good idea or not, but: we could also split the auto-attach unit out into a separate binary package (say, `ubuntu-pro-attach`, for argument's sake).  So the `ubuntu-advantage-tools` package won't _ever_ auto-attach, and the Pro image builds opt into auto-attach by installing `ubuntu-pro-attach`.

**Comment by blackboxsw** [comment]
That suggestion is compelling due to the fact that we own the image creation process, it'd allow us to keep the ua client cloud_detection logic and systemd/init scripts simple. 

This raises the question about doing something even more simple than creating and maintaining a separate package:
 * since we own the PRO image build process. Couldn't we just have a marker file/environment variable/artifact on the filesystemon images that 'should' be Ubuntu PRO? If marker file/variable is present, then we assume we are an Ubuntu PRO image (or derived from an Ubuntu PRO image).
 * Another alternative is extending is_viable() to grow smarts to parse some part of identity_doc to determine if something in cloud meta-data can indicate to the VM that it's an Ubuntu Pro offering before trying to confirm against ua-contract server

**Comment by OddBloke** [comment]
On Wed, Feb 05, 2020 at 01:47:31PM -0800, Chad Smith wrote:
> That suggestion is compelling due to the fact that we own the image
> creation process, it'd allow us to keep the ua client cloud_detection
> logic and systemd/init scripts simple.
> 
> This raises the question about doing something even more simple than
> creating and maintaining a separate package:

To be clear, I'm proposing a separate binary package in the
ubuntu-advantage-tools source package, so the creation cost and
maintenance burden should be relatively minimal.

>  * since we own the PRO image build process. Couldn't we just have a
>    marker file/environment variable/artifact on the filesystem on
>    images that 'should' be Ubuntu PRO? If marker file/variable is
>    present, then we assume we are an Ubuntu PRO image (or derived from
>    an Ubuntu PRO image).

We could do this, yeah.  I would lean towards the package option for a
few reasons:

* with a package, if there were other Pro-specific things that we wanted
  to do, then we would have a natural place for them to live[0] which
  wouldn't involve modifying the image build process
* the image build process has been moving away from dropping arbitrary
  files in images, in part because there isn't any way to upgrade the
  arbitrary files in an image; this wouldn't be an issue _now_, but if
  we did want to do more complex Pro-related stuff, then this could be
  important[1]
* we wouldn't be installing a systemd unit that amounts to cruft in most
  deployments
* we wouldn't be installing a "useless" flag file on Pro images, we
  would only be installing the systemd unit

[0] The most obvious example that occurs to me: if we wanted to have a
    MOTD message about Ubuntu Pro, we could simply add that to the
    packaging that only gets installed on Pro instances.  We wouldn't
    have to write any dynamic logic.
[1] To continue from [0], if we dropped the MOTD snippet in during image
    build, then changes only take effect for _new images_.  So if, say,
    we notice a typo in the MOTD, then we have no way of upgrading that
    message on already-deployed instances.

>  * Another alternative is extending is_viable() to grow smarts to
>    parse some part of identity_doc to determine if something in cloud
>    meta-data can indicate to the VM that it's an Ubuntu Pro offering
>    before trying to confirm against ua-contract server

I think this is a risky path to go down, because it entangles the
publication of Ubuntu Pro images with the contents of those images.
Currently, only ua-contracts needs to be kept up-to-date with
publication changes and, as a managed service, that's of course much
easier to update.

**Comment by powersj** [comment]
+1 to the new binary package

To bike shed can we call it `ubuntu-advantage-pro`

**Comment by OddBloke** [comment]
Chad and I need to discuss what the steps forward here are.
